In [1]:
import tensorflow as tf

#### 创建一张图包含一组op和tensor，上下文环境

In [2]:
# op：只要石永红个TensorFlow的API定义的函数都是op
# tensor：指代的就是数据
g = tf.Graph()
print(g)

In [3]:
with g.as_default():
    c = tf.constant(11.0)
    print(c.graph)

#### 实现一个加法运算

In [4]:
a = tf.constant(5.0)
b = tf.constant(6.0)
sum1 = tf.add(a,b)

#### 默认的这张图，可相当于是给程序分配的一段内存

In [5]:
graph = tf.get_default_graph()
print(graph)

In [6]:
with tf.Session() as sess:
    print(sess.run(sum1))
    print(a.graph)
    print(sum1.graph)
    print(sess.graph)

11.0


In [7]:
plt = tf.placeholder(tf.float32,[None,3])

In [8]:
print(plt)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [9]:
with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
    print((sess.run(plt,feed_dict={plt:[[1,2,3],[4,5,6],[2,3,4]]})))
    print(sum1.eval)
    print(a.graph)
    print("-----shape-----")
    print(a.shape)
    print("-----op-----")
    print(a.op)

[[1. 2. 3.]
 [4. 5. 6.]
 [2. 3. 4.]]
<bound method Tensor.eval of <tf.Tensor 'Add:0' shape=() dtype=float32>>
-----shape-----
()
-----op-----
name: "Const"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_FLOAT
      tensor_shape {
      }
      float_val: 5.0
    }
  }
}



tensorflow打印出来的shape表示

0维 （）；1维（5）；2维（5,6）；3维 （3,4,5）

#### 形状的概念

静态形状和动态形状

In [10]:
plt = tf.placeholder(tf.float32,[None,2])
print(plt)

Tensor("Placeholder_1:0", shape=(?, 2), dtype=float32)


In [11]:
plt.set_shape([3,2])

In [12]:
print(plt)

Tensor("Placeholder_1:0", shape=(3, 2), dtype=float32)


plt.set([4,2]) 能再次改变形状吗?不能！对于静态形状而言，一旦张量形状固定了看，就不能再次设置静态形状,也不能跨维度修改形状；而动态形状可以去创建一个新的张量，改变的时候一定要注意元素数量要匹配：1D->2D 2d->3D 1D->3D等。

In [13]:
zero = tf.zeros([3,4],tf.float32)
zero.eval

<bound method Tensor.eval of <tf.Tensor 'zeros:0' shape=(3, 4) dtype=float32>>

In [14]:
zero = tf.ones([3,4],tf.float32)
zero.eval

<bound method Tensor.eval of <tf.Tensor 'ones:0' shape=(3, 4) dtype=float32>>

In [24]:
a = tf.cast([[1,2,3],[4,5,6]],tf.float32)
a.eval()

SyntaxError: invalid syntax (<ipython-input-24-ef78adbb662c>, line 2)